print("a(x**2) + b(x) + c = 0")
print("Enter the values of a,b,c")
a = int(input("Enter the value of a:"))
b = int(input("Enter the value of b:"))
c = int(input("Enter the value of c:"))
d = b**2 - 4*(a*c)
x = (-b - (d**0.5))/(2*a)
y = (-b + (d**0.5))/(2*a)
print("The roots of the equation are :",x,"and", y)
